site_name: Transform Tools Addon

nav:
  - 'Full Version': 'index.md'      # Changed 'Documentation' to 'Main Version (full)' for clarity
  - 'Lite Version': 'lite/index.md'  # Added this new line for the core docs
  - 'Core Version': 'core/index.md'  # Added this new line for the core docs

theme:
  name: material
  features:
    - toc.integrate

extra_css:
  - css/custom.css
