name: Deploy Docs # A name for this workflow

on:
  push:
    branches: # Trigger this workflow whenever changes are pushed to these branches
      - main # Or 'master', depending on your main branch name

# Sets permissions for GitHub Actions to create and deploy to GitHub Pages
permissions:
  contents: read  # Allow the workflow to read files (for checkout)
  pages: write    # Allow the workflow to deploy to Pages
  id-token: write # Allow authentication with OIDC (required for deploy-pages)

jobs:
  # Build job: Builds the documentation website
  build:
    runs-on: ubuntu-latest # Use a standard Linux runner provided by GitHub
    steps:
      - name: Checkout code # Get the files from your repository
        uses: actions/checkout@v4

      - name: Setup Python # Set up Python on the runner
        uses: actions/setup-python@v5
        with:
          python-version: 3.x # Use a recent Python version

      - name: Install MkDocs and theme # Install the necessary tools
        run: pip install mkdocs mkdocs-material

      - name: Build documentation # Run MkDocs to build the website
        run: mkdocs build --clean # --clean removes old files before building into ./site

      # Step to upload the built documentation as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3 # Use the official upload action
        with:
          path: ./site # The directory containing the built site files (created by mkdocs build)


  # Deploy job: Deploys the artifact to GitHub Pages
  deploy:
    environment: # This job is linked to the GitHub Pages deployment environment
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Get the deployed URL after success

    runs-on: ubuntu-latest # Use a standard Linux runner
    needs: build # This job requires the 'build' job to complete successfully

    steps:
      # Step to deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment # Give this step an ID to reference its output (the URL)
        uses: actions/deploy-pages@v4 # Use the official deploy action